### ISSUE TITLE
Create boss

### ISSUE THREAD

**Issue by Jazy5552** [cap4053-cheeky-pixels/EmbodyGame#44]
Create a boss for the game. Boss mechanics are still up for discussion and suggestions can be added to this issue. Add boss health to the HUD.

Behavior checklist:

- [x] Flying towards the player
- [x] Triggering flight when the player is out of the ranged attack zone
- [x] Triggering melee attacks when player within melee range
- [x] Triggering ranged attacks when player within ranged attack zone but outside melee
- [x] Playing damage recoil animation when the boss is hurt (not always)
- [x] Playing stunned animation when the boss hits half health
- [x] Transitioning to a Phase 2, with increased difficulty (not a priority)
- [x] Playing death animation when the boss hits 0 health
- [x] Playing victory animation when the player is defeated
- [x] Facing the player when attacking or idle

**Comment by Jazy5552** [comment]
Draft for boss
```
Once boss is awake...

What should it do?

Well, first fly towards the player?
Start ranged attacks?

How about this: give the boss a certain radius within which it can attack with ranged.
If the player is within that radius, then simply throw fireballs.
If not, then start moving towards the player ("fly").

If, however, the player is within melee range, then start stabbing with pitchfork.

Don't stab and fireball at the same time... so maybe just have a flag called "attacking"
that gets flipped to true if you're fireballing or stabbing. Both attacks will loop their
animations. 

Be sure to put attack animations on loop!

What if player enters melee range, and exits?

OnTriggerExit for melee: attacking = false
OnTriggerStay for ranged: if ! attacking, then SetTrigger("AttackRanged") and spawn fireballs
```

**Comment by AleksandrHovhannisyan** [comment]
#61
